### ISSUE TITLE
nutcracker-web does not work behind https...

### ISSUE THREAD

**Issue by ArcticSnowman** [kontera-technologies/nutcracker-web#10]
When the nutcracker-web is hosts behind a HTTPS  URL, the cluster/node pages do not work.   Using Chrome's inspection tool I see the following error:

`Mixed Content: The page at 'https://redis.example.com/#/clusters/intrds-dev3' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/jsapi'. This request has been blocked; the content must be served over HTTPS.`

There needs to be a means to tell the server it's behind https and have it switch the call to google.

**Comment by eranb** [comment]
Hi @ArcticSnowman, 
I Uploaded new version - `nutcracker-web-0.0.13.gem`.

tell me if its working from your side

**Comment by ArcticSnowman** [comment]
@eranb  Thanks , wIll let you know...

**Comment by ArcticSnowman** [comment]
Works great thanks..

**Comment by eranb** [comment]
@ArcticSnowman np
