### ISSUE TITLE
Twemproxy updated nutcracker-web not running

### ISSUE THREAD

**Issue by vishalsharma13** [kontera-technologies/nutcracker-web#11]
Hi,

I have updated my nutcracker from https://github.com/vipshop/twemproxies and after that my nutcracker-web not running and after sometime it gives 504 error. So please suggest i need to update my nutcracker-web gem or anything else.

**Comment by eranb** [comment]
can you send me nutcracker-web log file ?

**Comment by vishalsharma13** [comment]
Hi @eranb 

No found any specific log file but at developer console of browser found below error.

https://XXXXX/favicon.ico Failed to load resource: the server responded with a status of 401 (Unauthorized)
nutcracker-web Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

**Comment by eranb** [comment]
how do you run nutcracker-web ?

**Comment by vishalsharma13** [comment]
Hi @eranb ,

Thanks for reply.

command :- nutcracker-web -c /home/cache/twemproxy-multithread/twemproxies-master/conf/nutcracker.yml --port 8514 --context nutcracker-web

nutcracker.yml :- 

alpha:
  auto_eject_hosts: false
  distribution: modula
  hash: crc32a
  hash_tag: '{}'
  listen: 0.0.0.0:8511
  preconnect: false
  redis: true
  server_connections: 10000
  server_failure_limit: 2
  server_retry_timeout: 30000
  servers:
  - 10.247.74.44:6381:1 master
  tcpkeepalive: true
  tcpkeepcnt: 5
  tcpkeepidle: 2700
  tcpkeepintvl: 60
  timeout: 500
beta:
  auto_eject_hosts: false
  distribution: modula
  hash: crc32a
  hash_tag: '{}'
  listen: 0.0.0.0:8510
  preconnect: false
  redis: true
  server_connections: 10000
  server_failure_limit: 10
  server_retry_timeout: 30000
  servers:
  - 10.247.74.38:6380:1 slave1
  - 10.247.74.51:6382:1 slave2
  tcpkeepalive: true
  tcpkeepcnt: 5
  tcpkeepidle: 2700
  tcpkeepintvl: 60
  timeout: 1000

Gem List :- 

bigdecimal (1.2.0)
bundler (1.13.7)
haml (4.0.7)
io-console (0.4.2)
json (1.7.7)
nutcracker (0.4.1.20)
nutcracker-web (0.0.12)
psych (2.0.0)
rack (1.6.4)
rack-protection (1.5.3)
rdoc (4.0.0)
redis (3.3.2)
sinatra (1.4.7)
tilt (1.4.1)

nutcracker-web version :- Nutcracker-Web, Ver. 0.0.12

**Comment by eranb** [comment]
while nutcracker-web is running, can you please send me the output of

**Comment by vishalsharma13** [comment]
No output (Internet is not working on my server)

**Comment by eranb** [comment]
It's strange, it's not related to internet/network, because you send the request to `localhost` ( which is the loopback interface ) so the request doesn't even leave your network card.
can you run it again with `-vvv` like so:
`curl -vvv http://localhost:8514/nutcracker-web`
* don't forget to make sure `nutcracker-web` is running, before you send the curl request

**Comment by vishalsharma13** [comment]
Output 

curl -vvv http://localhost:8514/nutcracker-web
* About to connect() to localhost port 8514 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8514 (#0)
> GET /nutcracker-web HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8514
> Accept: */*
>

process :- 

tcp        0      0 0.0.0.0:8514            0.0.0.0:*               LISTEN      26492/ruby

Threads :- 

26492 26492 ?        00:00:00 nutcracker-web
26492 26497 ?        00:00:08 nutcracker-web
26492 26500 ?        00:00:26 nutcracker-web
26492  8493 ?        00:00:00 nutcracker-web
26492  8504 ?        00:00:00 nutcracker-web
26492  8523 ?        00:00:00 nutcracker-web
26492  9996 ?        00:00:00 nutcracker-web
26492  9997 ?        00:00:00 nutcracker-web
26492 10000 ?        00:00:00 nutcracker-web

command :- 

cache    26492     1  0 Feb28 ?        00:00:35 /usr/bin/ruby /home/cache/bin/nutcracker-web -c /home/cache/twemproxy-multithread/twemproxies-master/conf/nutcracker.yml --port 8514 --context nutcracker-web

**Comment by eranb** [comment]
OK, I think I know what may cause it, in order `nutcracker-web` will function well it need connectivity to all of the components involve, you need to make you have connectivity to:
1.Twemproxy stats: default stats port is 22222, if you run your Twemproxy with different stats port, don't forget to change it:
`curl -vvv TwemproxyHost:22222`

We need make sure nu


can you please run this commands and send me the output:
`curl -vvv localhost:2222` 
`redis-cli -p 10.247.74.38:6380`
`10.247.74.51:6382`
`0.247.74.44:6381`

**Comment by vishalsharma13** [comment]
It working fine now , issue was in latest nutcracker and rollback to previous nutcracker version and its running.

Thank You for your support.

**Comment by eranb** [comment]
np
