### ISSUE TITLE
Warning while install nutcracker-web gem

### ISSUE THREAD

**Issue by vishalsharma13** [kontera-technologies/nutcracker-web#12]
@eranb 

While installing update of nutcracker-web gem and i am getting below warning. Please suggest if below warning is important and required other dependencies to install.

WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/latest_specs.4.8.gz)

**Comment by eranb** [comment]
Hi @vishalsharma13,
It's seems like a network error or some issue with `rubygems.org` and not related to the gem.
