### ISSUE TITLE
Seeing a lot of Zeros

### ISSUE THREAD

**Issue by joe-at-startupmedia** [kontera-technologies/nutcracker-web#13]
Seeing a lot of zeros when launching my instance. Would this have to do with the maxmemory attribute not being set in the redis.conf?

![img](https://content.screencast.com/users/JosephPersie/folders/Jing/media/703b4556-eded-4c94-8041-11098067d636/00000001.png)

**Comment by joe-at-startupmedia** [comment]
INFO Command in the redis instance (pertaining to the screenshot above) yields the following:

127.0.0.1:6379> INFO
# Server
redis_version:3.2.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:c8b45a0ec7dc67c6
redis_mode:standalone
os:Linux 3.10.0-693.17.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.5
process_id:752
run_id:4985568f70d088860da227d0c894dfd30ae0f4b1
tcp_port:6379
uptime_in_seconds:15892118
uptime_in_days:183
hz:10
lru_clock:8823366
executable:/usr/bin/redis-server
config_file:/etc/redis-001.conf

# Stats
total_connections_received:849451
total_commands_processed:296922784
instantaneous_ops_per_sec:32
total_net_input_bytes:29759216794
total_net_output_bytes:28826136206
instantaneous_input_kbps:3.44
instantaneous_output_kbps:1.19
rejected_connections:0
sync_full:1
sync_partial_ok:1
sync_partial_err:0
expired_keys:1292261
evicted_keys:0
keyspace_hits:1302159
keyspace_misses:57075886
pubsub_channels:5
pubsub_patterns:0
latest_fork_usec:1079
migrate_cached_sockets:0

# Memory
used_memory:101140296
used_memory_human:96.45M
used_memory_rss:110866432
used_memory_rss_human:105.73M
used_memory_peak:101733832
used_memory_peak_human:97.02M
total_system_memory:1928765440
total_system_memory_human:1.80G
used_memory_lua:64512
used_memory_lua_human:63.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.10
mem_allocator:jemalloc-3.6.0

**Comment by eranb** [comment]
@joe-at-startupmedia yes.
https://github.com/kontera-technologies/nutcracker-web#gotchas

**Comment by joe-at-startupmedia** [comment]
@eranb  Setting unfortunately setting the maxmemory does not resolve the issue:

```

# Memory
used_memory:2755968
used_memory_human:2.63M
used_memory_rss:14491648
used_memory_rss_human:13.82M
used_memory_peak:7730112
used_memory_peak_human:7.37M
total_system_memory:1928765440
total_system_memory_human:1.80G
used_memory_lua:46080
used_memory_lua_human:45.00K
maxmemory:209715200
maxmemory_human:200.00M
maxmemory_policy:noeviction
mem_fragmentation_ratio:5.26
mem_allocator:jemalloc-3.6.0
```

Are there any other settings that could be causing this issue?

**Comment by joe-at-startupmedia** [comment]
I've noticed the output of the stats command does not contain the `info` block for each servers as provided in your example.json. How are you populating the info block?
```
{
	"service": "nutcracker",
	"source": "twemproxy",
	"version": "0.4.1",
	"uptime": 450,
	"timestamp": 1536265819,
	"total_connections": 37,
	"curr_connections": 31,
	"alpha": {
		"client_eof": 6,
		"client_err": 0,
		"client_connections": 16,
		"server_ejects": 0,
		"forward_error": 0,
		"fragments": 0,
		"redis-002": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 32,
			"request_bytes": 1524,
			"responses": 32,
			"response_bytes": 3694,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-003": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 77,
			"request_bytes": 3536,
			"responses": 77,
			"response_bytes": 30264,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-004": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 42,
			"request_bytes": 1860,
			"responses": 42,
			"response_bytes": 54524,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-005": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 36,
			"request_bytes": 1670,
			"responses": 36,
			"response_bytes": 5282,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}
	}
}
```

**Comment by eranb** [comment]
@joe-at-startupmedia can you send me nutcracker-web response ? 
open nutcracker-web in the browser -> view source -> copy the `json` object that is embedded in `data-clusters` div.
Please make sure you don't have any sensitive data before you post it.

**Comment by joe-at-startupmedia** [comment]
## Nutcracker overview.json

`curl 0.0.0.0/overview.json`

```
{
	"clusters": [{
		"nodes": [{
			"server_url": "redis://10.132.16.48:6380",
			"info": {},
			"running": false,
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 7291,
			"request_bytes": 356551,
			"responses": 7291,
			"response_bytes": 1263694,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}, {
			"server_url": "redis://10.132.16.48:6381",
			"info": {},
			"running": false,
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 24235,
			"request_bytes": 1081089,
			"responses": 24235,
			"response_bytes": 6328309,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}, {
			"server_url": "redis://10.132.16.48:6382",
			"info": {},
			"running": false,
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 13693,
			"request_bytes": 622267,
			"responses": 13693,
			"response_bytes": 11100127,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}, {
			"server_url": "redis://10.132.16.48:6383",
			"info": {},
			"running": false,
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 5065,
			"request_bytes": 231284,
			"responses": 5065,
			"response_bytes": 449463,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}],
		"name": "alpha",
		"client_eof": 3960,
		"client_err": 0,
		"client_connections": 27,
		"server_ejects": 0,
		"forward_error": 0,
		"fragments": 0
	}, {
		"nodes": [{
			"server_url": "redis://10.132.169.170:6379",
			"info": {},
			"running": false,
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 22939,
			"request_bytes": 2818061,
			"responses": 22939,
			"response_bytes": 1833160,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}],
		"name": "georedis",
		"client_eof": 18,
		"client_err": 0,
		"client_connections": 18,
		"server_ejects": 0,
		"forward_error": 0,
		"fragments": 0
	}],
	"config": {
		"alpha": {
			"listen": "0.0.0.0:22122",
			"hash": "fnv1a_64",
			"hash_tag": "{}",
			"distribution": "ketama",
			"auto_eject_hosts": true,
			"server_retry_timeout": 30000,
			"server_failure_limit": 3,
			"timeout": 400,
			"redis": true,
			"preconnect": true,
			"redis_auth": "XXXXXXXXXXXXX",
			"servers": ["10.132.16.48:6380:1 redis-002", "10.132.16.48:6381:1 redis-003", "10.132.16.48:6382:1 redis-004", "10.132.16.48:6383:1 redis-005"]
		},
		"georedis": {
			"listen": "0.0.0.0:22123",
			"hash": "fnv1a_64",
			"distribution": "ketama",
			"auto_eject_hosts": true,
			"server_retry_timeout": 30000,
			"server_failure_limit": 3,
			"timeout": 3000,
			"redis": true,
			"preconnect": true,
			"redis_auth": "XXXXXXXXXXXXX",
			"servers": ["10.132.169.170:6379:1 redis-001"]
		}
	},
	"service": "nutcracker",
	"source": "startup-twemproxy",
	"version": "0.4.1",
	"uptime": 366811,
	"timestamp": 1537317470,
	"total_connections": 4030,
	"curr_connections": 52
}
```

## Twemproxy Stats

`$ curl 0.0.0.0:22222` 

```
{
	"service": "nutcracker",
	"source": "twemproxy-hostname",
	"version": "0.4.1",
	"uptime": 366952,
	"timestamp": 1537317611,
	"total_connections": 4032,
	"curr_connections": 52,
	"alpha": {
		"client_eof": 3962,
		"client_err": 0,
		"client_connections": 27,
		"server_ejects": 0,
		"forward_error": 0,
		"fragments": 0,
		"redis-002": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 7293,
			"request_bytes": 356635,
			"responses": 7293,
			"response_bytes": 1263704,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-003": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 24246,
			"request_bytes": 1081556,
			"responses": 24245,
			"response_bytes": 6338350,
			"in_queue": 1,
			"in_queue_bytes": 42,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-004": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 13704,
			"request_bytes": 622738,
			"responses": 13704,
			"response_bytes": 11117827,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		},
		"redis-005": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 5070,
			"request_bytes": 231495,
			"responses": 5070,
			"response_bytes": 449488,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}
	},
	"georedis": {
		"client_eof": 18,
		"client_err": 0,
		"client_connections": 18,
		"server_ejects": 0,
		"forward_error": 0,
		"fragments": 0,
		"redis-001": {
			"server_eof": 0,
			"server_err": 0,
			"server_timedout": 0,
			"server_connections": 1,
			"server_ejected_at": 0,
			"requests": 22939,
			"request_bytes": 2818061,
			"responses": 22939,
			"response_bytes": 1833160,
			"in_queue": 0,
			"in_queue_bytes": 0,
			"out_queue": 0,
			"out_queue_bytes": 0
		}
	}
}
```

**Comment by eranb** [comment]
It seems like connectivity issue between the node that runs Nutcracker-web to the Redis instance ( not to tmproxy ).
If you have redis-cli installed in ***nutcracker-web*** machine, you can check it via:
```
redis-cli -h 10.132.16.48 -p 6380
```

**Comment by eranb** [comment]
You run `nutcracker-web` on the machine that runs `Twemproxy` ?

**Comment by eranb** [comment]
> My first question would be why is running false and where does it come from. I look in the gems and it appears to be coming from the nutcracker gem on the following line:
> 
> ```ruby
>     def running?
>       attached? ? stats.any? : !!(pid and ::Process.getpgid pid rescue nil)
>     end
> ```
it should return true if it managed to get the stats from twemproxy (`stats.any?`).
so if it returns false either `attached?` return false or `stats.any?` return false
can you edit the source file and add this line - 
`puts({stats: stats, attached: attached?}.inspect)` 
before line `196`
https://github.com/kontera-technologies/nutcracker/blob/master/lib/nutcracker.rb#L196 
and also comment these two lines:
https://github.com/kontera-technologies/nutcracker/blob/master/lib/nutcracker.rb#L146-L147
> 
> One thing to note is that I am not launching Twemproxy using nutcracker web, I am only running it connecting to an existing instance.
> 
> ```shell
> $ nutcracker-web --config /etc/nutcracker/cluster.yml --port 22122
> ```
its ok, when you run it like that the `attached?` variable inside the `running?` func should return true.
> 
> How would the nutcracker dependency know about my pid If I did not use it to launch? Ruby is not my language of choice so I don't know what that line means, looks like a ternary operator.
> 
it doesn't because its running in `attached` mode and its not using Twemproxy `pid` 
> In the meantime I was able to get my current architectural configuration monitored using
> https://github.com/LittlePeng/redis-monitor

**Comment by joe-at-startupmedia** [comment]
See commit below which solved my issue.

**Comment by eranb** [comment]
Thanks for https://github.com/kontera-technologies/nutcracker/pull/4

Upload new versions with your fix plus better error message:
- `nutcracker-0.4.1.23`
- `nutcracker-web-0.0.15`
