### ISSUE TITLE
Explain the error on nutcracker-web 

### ISSUE THREAD

**Issue by brijesh27** [kontera-technologies/nutcracker-web#6]
Please explain the below errors on nutcracker webinterface: 
1. Client EOF : what does it mean on nutcracker dashboard
2. Forward Errors : 
3.  Fragments 

I have install nutcracker-web but observing the client EOF and forward errors increased so please let me what are these 3 in-terms of nutcracker/redis

**Comment by eranb** [comment]
@brijesh27 I just exposed the errors I get from `twemproxy` process, you can find more info about these fields here https://github.com/twitter/twemproxy#observability

**Comment by brijesh27** [comment]
Thanks Eranb, 
Below is still not clear. 
  client_eof          "# eof on client connections"   , didn't get this one 
  forward_error       "# times we encountered a forwarding error"   [  this means nutcracker was not able to forward the client request to redis server or any thing else  ]

**Comment by eranb** [comment]
client_eof: means client END OF FILE the connection between nutcracker and the redis instance was closed from some reason, try to check both redis and nutcracker logs.
http://stackoverflow.com/questions/1321619/what-does-end-of-file-on-a-socket-mean

forward_error: something internal to nutcracker impl

If it still not clear you should ask for more information from `twemproxy` guys
https://github.com/twitter/twemproxy/issues

**Comment by brijesh27** [comment]
Thanks Eranb

**Comment by brijesh27** [comment]
how we can get logging enable with nutcracker-web ,  any config file where we can define the twem-proxy log file with nutcracker-web .

**Comment by eranb** [comment]
1. about the logging, first read the section: "To build twemproxy from source with debug logs enabled and assertions enabled:" 
https://github.com/twitter/twemproxy
after you compiled it with debug enable and install it (via `make install` or something), just run it with verbose mode:
`nutcracker -c conf/nutcracker.yml --verbose 11` 
then  connect `nutcracker-web` to twemproxy server via:
`nutcracker-web --config conf/nutcracker.yml --port 22122`
2. about the stats flush, I've no idea other than restart twemproxy server, you will need to ask twemproxy guys

**Comment by brijesh27** [comment]
Thanks Eranb, 
It's working fine now and logging also working fine. 
After changing the port  in nutcracker.yml as we are using 22122 port for nutcracker-web , every thing working fine.
